attr_file: selected_cartoonset100k/cartoon_attr.txt
image_dir: selected_cartoonset100k/images/

manual_seed: 636

batch_size: 64
num_epoch: 5000

arch: noinpute
n_critic: 4
noise_dim: 100
num_all_labels: 15
base_acti_maps: 32

lr: 1e-4
beta1: 0.0
beta2: 0.9
